#ifndef MECS_CONSTANTS_H
#define MECS_CONSTANTS_H

#ifndef MECS_ENTITIES_CAPACITY
#define MECS_ENTITIES_CAPACITY 128
#endif

#ifndef MECS_COMPONENTS_CAPACITY
#define MECS_COMPONENTS_CAPACITY 32
#endif

#endif
